# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataflow_graph.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x61taflow_graph.proto\"\x9a\x01\n\x06Kernel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\r\n\x05outer\x18\x03 \x01(\x05\x12\t\n\x01M\x18\x04 \x01(\x05\x12\t\n\x01K\x18\x05 \x01(\x05\x12\t\n\x01N\x18\x06 \x01(\x05\x12 \n\x04type\x18\x07 \x01(\x0e\x32\x12.Kernel.KernelType\"$\n\nKernelType\x12\x0c\n\x08SYSTOLIC\x10\x00\x12\x08\n\x04SIMD\x10\x01\"\xa7\x01\n\x06\x42uffer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x13\n\x0btensor_size\x18\x03 \x01(\x05\x12\x10\n\x08startIdx\x18\x04 \x01(\x05\x12\x0e\n\x06\x65ndIdx\x18\x05 \x01(\x05\x12 \n\x04type\x18\x06 \x01(\x0e\x32\x12.Buffer.BufferType\"*\n\nBufferType\x12\n\n\x06WEIGHT\x10\x00\x12\x10\n\x0cINTERMEDIATE\x10\x01\"D\n\x0e\x44\x61taflow_Graph\x12\x18\n\x07kernels\x18\x01 \x03(\x0b\x32\x07.Kernel\x12\x18\n\x07\x62uffers\x18\x02 \x03(\x0b\x32\x07.Bufferb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dataflow_graph_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KERNEL._serialized_start=25
  _KERNEL._serialized_end=179
  _KERNEL_KERNELTYPE._serialized_start=143
  _KERNEL_KERNELTYPE._serialized_end=179
  _BUFFER._serialized_start=182
  _BUFFER._serialized_end=349
  _BUFFER_BUFFERTYPE._serialized_start=307
  _BUFFER_BUFFERTYPE._serialized_end=349
  _DATAFLOW_GRAPH._serialized_start=351
  _DATAFLOW_GRAPH._serialized_end=419
# @@protoc_insertion_point(module_scope)
